[build]
  command = "cd ../pdf && npm install && node generate-resume.js && cp output/Cameron_Green_Resume.pdf ../nextjs/public/assets/Resume.pdf && cd ../nextjs && npm run build"

[context.production]
  command = "cd ../pdf && npm install && node generate-resume.js && cp output/Cameron_Green_Resume.pdf ../nextjs/public/assets/Resume.pdf && cd ../nextjs && npm run build"

[context.deploy-preview]
  command = "cd ../pdf && npm install && node generate-resume.js && cp output/Cameron_Green_Resume.pdf ../nextjs/public/assets/Resume.pdf && cd ../nextjs && npm run build"

[context.branch-deploy]
  command = "cd ../pdf && npm install && node generate-resume.js && cp output/Cameron_Green_Resume.pdf ../nextjs/public/assets/Resume.pdf && cd ../nextjs && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
